name: Boot Cloud Phone

on:
  workflow_dispatch:

jobs:
  boot-cloud-phone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Make Bash Scripts Executable
        run: chmod +x bash/*.sh

      - name: Boot Cloud Phone
        run: bash bash/booting.sh

      - name: Simulate Fast Charging 55W
        run: bash bash/charging_55w.sh
