name: Discharging Battery

on:
  workflow_dispatch:

jobs:
  discharging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Ensure ADB is installed
        run: |
          sudo apt-get update
          sudo apt-get install -y adb

      - name: Make discharging script executable
        run: chmod +x scripts/discharging.sh

      - name: Run Discharging Script
        run: bash scripts/discharging.sh
